version: '3.9'

services:
  bookkeeper.ui:
    image: ${DOCKER_REGISTRY-}bookkeeperui
    container_name: BookKeeper.UI
    build:
      context: .
      dockerfile: src/BookKeeper.UI/Dockerfile
    ports:
      - 5000:8080
      - 5001:8081 

  bookkeeper.database:
    image: postgres:latest
    container_name: BookKeeper.Database
    environment:
      - POSTGRES_DB=bookkeeper
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./.containers/db:/var/lib/postgresql/data
    ports:
      - 5432:5432

  bookkeeper.seq:
    image: datalust/seq:latest
    container_name: BookKeeper.Seq
    environment:
      - ACCEPT_EULA=Y
    ports:
      - 5341:5341
      - 8081:80