version: '3.9'

services:
  bookkeeper.ui:
    image: ${DOCKER_REGISTRY-}bookkeeperui
    container_name: BookKeeper.UI
    build:
      context: .
      dockerfile: src/BookKeeper.UI/Dockerfile
    ports:
      - 5000:8080
      - 5001:8081 
